import subprocess
import serial
import time
import csv
import os

# --- Configuration ---
GOLDEN_BITSTREAM = "../neo_tpu_golden.bit"
UART_PORT = "/dev/ttyUSB0"      # Address to UART port
BAUD_RATE = 921600
TEST_ITERATIONS = 10            # To be set to 10,000 for full campaign
EXPECTED_HASH = "c32527e5"      # Hash generated by GOLDEN_BITSTREAM
CORRUPT_BITSTREAMS = "../corrupt_bit"
TEST_RESULTS = "../fault_test_results.csv"
TIMEOUT_SEC = 30                # 30-second fatal crash timeout

def run_fault_campaign():
    print("Starting Fault Injection Campaign...")
    
    # 1. Open the physical UART port
    try:
        ser = serial.Serial(UART_PORT, BAUD_RATE, timeout=TIMEOUT_SEC)
    except serial.SerialException as e:
        print(f"Error opening UART: {e}")
        return

    # 2. Open a CSV file to store the statistics for all 10,000 runs
    with open(TEST_RESULTS, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        # Write the header row
        writer.writerow(['Test_ID', 'Corrupt_Bit_File', 'UART_OUTPUT', 'Status'])

        # 3. Main Testing Loop
        for i in range(TEST_ITERATIONS):
            corrupt_bit_file = f"{CORRUPT_BITSTREAMS}/fi_bit_{i}.bit"

            try:
                # --- STEP A: Bitstream Corruption ---
                # Using subprocess to call the lab's "pixel" tool in the terminal.
                # (You will need to adjust the arguments to match how 'pixel' actually works)
                subprocess.run(["pixel", "--input", GOLDEN_BITSTREAM, "--output", corrupt_bit_file], 
                                check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
                
                # --- STEP B: Flash the Board ---
                # Call Vivado's XSCT tool. We pass it a small Tcl script that handles the JTAG connection.
                subprocess.run(["xsct", "program_fpga.tcl", corrupt_bit_file], 
                                check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
                    
                # --- STEP C: Smart UART Read ---
                ser.reset_input_buffer()
                
                # We read until we hit a newline. If the board is dead, this hangs until TIMEOUT_SEC expires.
                # We loop a few times in case the expected hash is printed on the 3rd or 4th line.
                start_time = time.time()
                while (time.time() - start_time) < TIMEOUT_SEC:
                    # Read a line (blocks up to TIMEOUT_SEC)
                    line = ser.readline().decode('utf-8', errors='ignore')
                    uart_o += line
                    
                    if EXPECTED_HASH in uart_o:
                        status = "PASS"
                        break # Exit the loop immediately! No sleeping!
                
                # If the loop finished and we didn't get a PASS, it timed out or printed garbage
                if status != "PASS":
                    if uart_o.strip() == "":
                        status = f"FATAL_CRASH (Timeout {TIMEOUT_SEC}s)"
                    else:
                        status = "HASH_MISMATCH"

            except subprocess.CalledProcessError as e:
                # This catches errors from pixel or xsct crashing
                status = f"TOOL_ERROR: {e.cmd[0]} failed"
                print(f"\n[!] Tool Error on iteration {i}:\n{e.stderr.decode('utf-8')}")
                
            writer.writerow([i, corrupt_bit_file, uart_o.strip(), status])
            print(f"Test {i}/{TEST_ITERATIONS} Completed | Status: {status}")

    ser.close()
    print(f"Campaign Complete. Results saved to {TEST_RESULTS}")

if __name__ == "__main__":
    # Ensure the output directory exists
    os.makedirs(CORRUPT_BITSTREAMS, exist_ok=True)
    run_fault_campaign()